name: mlx-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.3=py312he37b823_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.17=h382b9c6_2
  - aws-c-cal=0.6.11=hd34e5fa_0
  - aws-c-common=0.9.15=h93a5062_0
  - aws-c-compression=0.2.18=hd34e5fa_3
  - aws-c-event-stream=0.4.2=h247c08a_8
  - aws-c-http=0.8.1=hf9e830b_10
  - aws-c-io=0.14.7=h33d81b3_6
  - aws-c-mqtt=0.10.3=h5f4abda_4
  - aws-c-s3=0.5.7=h606a3d2_1
  - aws-c-sdkutils=0.1.15=hd34e5fa_3
  - aws-checksums=0.1.18=hd34e5fa_3
  - aws-crt-cpp=0.26.6=h13f0230_4
  - aws-sdk-cpp=1.11.267=h134aaec_6
  - brotli-python=1.1.0=py312h9f69965_1
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.28.1=h93a5062_0
  - ca-certificates=2024.2.2=hf0a4a13_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - datasets=2.19.0=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - fastapi=0.110.2=pyhd8ed1ab_0
  - filelock=3.13.4=pyhd8ed1ab_0
  - frozenlist=1.4.1=py312he37b823_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gflags=2.2.2=hc88da5d_1004
  - glog=0.7.0=hc6770e3_0
  - h11=0.14.0=pyhd8ed1ab_0
  - huggingface_hub=0.22.2=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.7=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - krb5=1.21.2=h92f50d5_0
  - libabseil=20240116.1=cxx17_hebf3989_2
  - libarrow=15.0.2=h3ee1d8f_3_cpu
  - libarrow-acero=15.0.2=h3f3aa29_3_cpu
  - libarrow-dataset=15.0.2=h3f3aa29_3_cpu
  - libarrow-flight=15.0.2=h224147a_3_cpu
  - libarrow-flight-sql=15.0.2=hb630850_3_cpu
  - libarrow-gandiva=15.0.2=h5fa1bb3_3_cpu
  - libarrow-substrait=15.0.2=hd92e347_3_cpu
  - libblas=3.9.0=22_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=22_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.7.1=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libgoogle-cloud=2.22.0=hbebe991_1
  - libgoogle-cloud-storage=2.22.0=h8a76758_1
  - libgrpc=1.62.2=h9c18a4f_0
  - libiconv=1.17=h0d3ecfb_2
  - liblapack=3.9.0=22_osxarm64_openblas
  - libllvm16=16.0.6=haab561b_3
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libparquet=15.0.2=h5304c63_3_cpu
  - libprotobuf=4.25.3=hbfab5d5_0
  - libre2-11=2023.09.01=h7b2c953_2
  - libsqlite=3.45.3=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.19.0=h026a170_1
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libxml2=2.12.6=h0d0cfa8_2
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=18.1.3=hcd81f8e_0
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=2.1.5=py312he37b823_0
  - mlx=0.11.1=py312h340368e_0
  - multidict=6.0.5=py312h670c8ac_0
  - multiprocess=0.70.16=py312he37b823_0
  - ncurses=6.4.20240210=h078ce10_0
  - numpy=1.26.4=py312h8442bc7_0
  - openssl=3.2.1=h0d3ecfb_1
  - orc=2.0.0=h4aad248_1
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py312h88edd18_0
  - pip=24.0=pyhd8ed1ab_0
  - protobuf=4.25.3=py312h1a610f3_0
  - pyarrow=15.0.2=py312h390c04e_3_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pydantic=2.7.0=pyhd8ed1ab_0
  - pydantic-core=2.18.1=py312h5280bc4_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.3=h4a7b5fc_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py312h02f2b3b_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h02f2b3b_1
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h92ec313_1
  - regex=2024.4.16=py312he37b823_0
  - requests=2.31.0=pyhd8ed1ab_0
  - safetensors=0.4.3=py312h5280bc4_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.0=hd04f947_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - starlette=0.37.2=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tokenizers=0.15.2=py312hfbf4c0d_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - transformers=4.39.3=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - uvicorn=0.29.0=py312h81bd7bf_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xxhash=0.8.2=hb547adb_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.4=py312he37b823_0
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - mlx-lm==0.12.1
      - mpmath==1.3.0
      - networkx==3.3
      - sentencepiece==0.2.0
      - sympy==1.12
      - torch==2.3.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/mlx
